name: Distribute iOS App to Firebase

on:
  push:
    tags:
      - 'v*'  # Only distribute on version tags like v1.0.0

jobs:
  distribute:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact (IPA)
        uses: actions/download-artifact@v3
        with:
          name: ios-build
          path: build

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Distribute IPA to Firebase
        run: |
          firebase appdistribution:distribute build/YourApp.ipa \
            --app ${{ secrets.S6P42TJUR7 }} \
            --token ${{ secrets.1//0g-rSnc2OtQKaCgYIARAAGBASNwF-L9IrWVLxnqMhyGH1nSxTtLuVAJUZCqe5GBgwge9DgQ1hu63p_WdGZzw_fqpSJpWbXyJ0uXQ }} \
            --groups "internal-testers" \
            --release-notes "Automated build from GitHub Actions"

